Update dump.yml

diff --git a/.github/workflows/dump.yml b/.github/workflows/dump.yml
--- a/.github/workflows/dump.yml
+++ b/.github/workflows/dump.yml
@@ -1,31 +1,25 @@
-# This is a basic workflow to help you get started with Actions
-
 name: CI
 
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
   push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
-
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
+    inputs:
+      input_url:
+        description: "Enter the file download URL"
+        required: true
+        type: string
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
     runs-on: ubuntu-20.04
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v4
+      - name: Checkout Code
+        uses: actions/checkout@v4
 
-      # Update package list and install necessary packages
       - name: Install Packages
         run: |
           sudo apt-get update
@@ -34,19 +28,61 @@ jobs:
             arj cabextract device-tree-compiler liblzma-dev python3-pip brotli \
             liblz4-tool axel gawk aria2 detox cpio rename liblz4-dev curl python3-venv
 
-      # Create a Python virtual environment and activate it
       - name: Set up Python environment and install packages
         run: |
           python3 -m venv .venv
           source .venv/bin/activate
           pip install aospdtgen backports.lzma extract-dtb protobuf pycryptodome docopt zstandard
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
+      - name: Define and Set URL
+        id: set_url
+        run: |
+          URL="${{ github.event.inputs.input_url }}"
+          if [[ "$URL" =~ ^https?://.*$ ]]; then
+            if [[ "$URL" =~ '1drv.ms' ]]; then
+              URL=$(curl -I "$URL" -s | grep location | sed -e "s/redir/download/g" -e "s/location: //g")
+            fi
+            echo "URL=$URL" >> $GITHUB_ENV
+          else
+            echo "Invalid URL provided"
+            exit 1
+          fi
+
+      - name: Download File
+        run: |
+          if command -v aria2c > /dev/null; then
+            aria2c -x16 -j"$(nproc)" "$URL"
+          else
+            wget -q --content-disposition --show-progress --progress=bar:force "$URL"
+          fi
+
+      - name: Extract and Process ROM File
+        run: |
+          FILE=$(echo "${URL##*/}" | detox)
+          EXTENSION=$(echo "${URL##*.}" | detox)
+          UNZIP_DIR=${FILE/.$EXTENSION/}
+
+          mkdir -p input working
+          mv "$FILE" "input/$FILE"
+
+          if [[ ! -d "Firmware_extractor" ]]; then
+            git clone -q --recurse-submodules https://github.com/AndroidDumps/Firmware_extractor
+          fi
+          if [[ ! -d "vmlinux-to-elf" ]]; then
+            git clone -q https://github.com/marin-m/vmlinux-to-elf
+          fi
+
+          bash Firmware_extractor/extractor.sh "input/$FILE" "working/$UNZIP_DIR"
+
+      - name: Extract Device Tree Blobs
+        run: |
+          if [[ -f "working/$UNZIP_DIR/boot.img" ]]; then
+            extract-dtb -o "working/$UNZIP_DIR/dtb" "working/$UNZIP_DIR/boot.img"
+          fi
+
+      - name: Run a One-line Script
         run: echo Hello, world!
 
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Finalize Processing
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          echo Processing complete.
